question_data = [{"type": "boolean", "difficulty": "easy", "category": "History",
                  "question": "The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Board Games",
                  "question": "When setting up a chess board, the king is placed on a square of his own color.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Geography",
                  "question": "St. Louis is the capital of the US State Missouri.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In &quot;Tony Hawk&#039;s Underground&quot;, the main character&#039;s friend turned rival is named &quot;Jeff Sampson&quot;",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment Video Games",
                  "question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
                  "question": "The Sun is considered a star.", "correct_answer": "True",
                  "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Animals",
                                                    "question": "Zebras are white with black stripes.",
                                                    "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "March 10th is also known as Mar10 Day.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Musicals &amp; Theatres",
                  "question": "In the play Oedipus Rex, Oedipus kills his father due to jealousy in loving his mother.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
